// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfNL1vqGK6eQZ_42sTf9xK3_CCH_z6-HE',
    appId: '1:240243238686:web:b2a17a2db61fb24d3c4b0f',
    messagingSenderId: '240243238686',
    projectId: 'todo-udemy-laiki',
    authDomain: 'todo-udemy-laiki.firebaseapp.com',
    storageBucket: 'todo-udemy-laiki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZX_QIyZnpqZqBfmoqYZRgRhB2hy2t7o',
    appId: '1:240243238686:android:11b6f47c8bf830673c4b0f',
    messagingSenderId: '240243238686',
    projectId: 'todo-udemy-laiki',
    storageBucket: 'todo-udemy-laiki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGr6y_GezuDirkp9-KCsS4Co0NhKPb0M',
    appId: '1:240243238686:ios:814145adfc83f5a33c4b0f',
    messagingSenderId: '240243238686',
    projectId: 'todo-udemy-laiki',
    storageBucket: 'todo-udemy-laiki.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGr6y_GezuDirkp9-KCsS4Co0NhKPb0M',
    appId: '1:240243238686:ios:814145adfc83f5a33c4b0f',
    messagingSenderId: '240243238686',
    projectId: 'todo-udemy-laiki',
    storageBucket: 'todo-udemy-laiki.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfNL1vqGK6eQZ_42sTf9xK3_CCH_z6-HE',
    appId: '1:240243238686:web:4f0273cf58ec9be13c4b0f',
    messagingSenderId: '240243238686',
    projectId: 'todo-udemy-laiki',
    authDomain: 'todo-udemy-laiki.firebaseapp.com',
    storageBucket: 'todo-udemy-laiki.appspot.com',
  );
}
